name: Release Scheduler

on:
  schedule:
    - cron: '15 13 * * WED' # Every Wed at 13:15pm UTC
  workflow_dispatch:

permissions:
  actions: write

jobs:
  dispatch_scheduled_releases:
    name: Dispatch scheduled releases
    if: ${{ github.repository_owner == 'spring-projects-experimental' }}
    strategy:
      matrix:
        # List of active maintenance branches.
        branch: [ main ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Dispatch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run update-scheduled-release-version.yml -r ${{ matrix.branch }}
